#include "head.h"
void korea(){ //한국 가로 31 세로 22
	gotoxy(13, 3);
	WHITE printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 4);
	WHITE printf("■■■■■■■■■"); BLACK printf("■"); WHITE printf("■■■■■■■■■■■"); BLACK printf("■"); WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 5);
	WHITE printf("■■■■■■■■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■■■■■■■■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■■■■■■■\n");
	gotoxy(13, 6);
	WHITE printf("■■■■■■■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■■■■■■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 7);
	WHITE printf("■■■■■■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■"); RED printf("■■■■■"); WHITE printf("■■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■");  BLACK printf("■"); WHITE printf("■■■■■■\n");
	gotoxy(13, 8);
	WHITE printf("■■■■■");  BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■"); RED printf("■■■■■■■■■");  WHITE printf("■■■");  BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■■■■\n");
	gotoxy(13, 9);
	WHITE printf("■■■■■■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■"); RED printf("■■■■■■■■■■■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■■■■■\n");
	gotoxy(13, 10);
	WHITE printf("■■■■■■■");  BLACK printf("■"); WHITE printf("■"); RED printf("■■■■■■■■■■■■■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■■■■■■\n");
	gotoxy(13, 11);
	WHITE printf("■■■■■■■■■"); RED printf("■■■■■■■■"); BLUE printf("■■"); RED printf("■■■"); WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 12);
	WHITE printf("■■■■■■■■■"); RED printf("■■■■■■■"); BLUE printf("■■■■"); RED printf("■■"); WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 13);
	WHITE printf("■■■■■■■■■"); BLUE printf("■■"); RED printf("■■■■"); BLUE printf("■■■■■■"); RED printf("■"); WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 14);
	WHITE printf("■■■■■■■■■"); BLUE printf("■■■■■■■■■■■■■"); WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 15);
	WHITE printf("■■■■■■■■■"); BLUE printf("■■■■■■■■■■■■■"); WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 16);
	WHITE printf("■■■■■■■"); BLACK printf("■"); WHITE printf("■■"); BLUE printf("■■■■■■■■■■■"); WHITE printf("■■"); BLACK printf("■"); WHITE printf("■■■■■■■\n");
	gotoxy(13, 17);
	WHITE printf("■■■■■■");  BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■"); BLUE printf("■■■■■■■■■"); WHITE printf("■■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■■■■■\n");
	gotoxy(13, 18);
	WHITE printf("■■■■■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■■"); BLUE printf("■■■■■"); WHITE printf("■■■■■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■■■■\n");
	gotoxy(13, 19);
	WHITE printf("■■■■■■"); BLACK printf("■"); WHITE printf("■■■"); BLACK printf("■"); WHITE printf("■■■■■■■■■"); BLACK printf("■"); WHITE printf("■■■"); BLACK printf("■"); WHITE printf("■■■■■■\n");
	gotoxy(13, 20);
	WHITE printf("■■■■■■■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■■■■■■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 21);
	WHITE printf("■■■■■■■■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■■■■■■■■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■■■■■■■■\n");
	gotoxy(13, 22);
	WHITE printf("■■■■■■■■■"); BLACK printf("■"); WHITE printf("■■■■■■■■■■■"); BLACK printf("■"); WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 23);
	WHITE printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
}


void USA(){  //미국
	gotoxy(13, 3);
	WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); RED; printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 4);
	DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); WHITE; printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 5);
	WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); RED; printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 6);
	DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); WHITE; printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 7);
	WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); RED; printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 8);
	DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); WHITE; printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 9);
	WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); RED; printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 10);
	DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); WHITE; printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 11);
	WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); RED; printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 12);
	DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); WHITE; printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 13);
	WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); RED; printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 14);
	DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); DARK_BLUE; printf("■"); WHITE; printf("★"); WHITE; printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 15);
	RED; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 16);
	WHITE; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 17);
	RED; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 18);
	WHITE; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 19);
	RED; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 20);
	WHITE; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 21);
	RED; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 22);
	WHITE; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
}  //미국


void India(){
	gotoxy(13, 5);
	YELLOW; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 6);
	YELLOW; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 7);
	YELLOW; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 8);
	YELLOW; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 9);
	YELLOW; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 10);
	WHITE; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 11);
	WHITE; printf("■■■■■■■■■■■"); BLUE; printf("■■■"); WHITE; printf("■■■■■■■■■■■\n");
	gotoxy(13, 12);
	WHITE; printf("■■■■■■■■■■"); BLUE; printf("■▧▥▨■"); WHITE; printf("■■■■■■■■■■\n");
	gotoxy(13, 13);
	WHITE; printf("■■■■■■■■■■"); BLUE; printf("■▤●▤■"); WHITE; printf("■■■■■■■■■■\n");
	gotoxy(13, 14);
	WHITE; printf("■■■■■■■■■■"); BLUE; printf("■▨▥▧■"); WHITE; printf("■■■■■■■■■■\n");
	gotoxy(13, 15);
	WHITE; printf("■■■■■■■■■■■"); BLUE; printf("■■■"); WHITE; printf("■■■■■■■■■■■\n");
	gotoxy(13, 16);
	WHITE; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 17);
	GREEN; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 18);
	GREEN; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 19);
	GREEN; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 20);
	GREEN; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 21);
	GREEN; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 22);
	GREEN; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
} //인도


void singapore(){ //싱가포르
	gotoxy(13, 3);
	RED; printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 4);
	RED; printf("■■■■■"); WHITE; printf("■■■"); RED; printf("■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 5);
	RED; printf("■■■"); WHITE; printf("■■■■"); RED; printf("■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 6);
	RED; printf("■■"); WHITE; printf("■■■■"); RED; printf("■■■■"); WHITE; printf("★"); RED; printf("■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 7);
	RED; printf("■■"); WHITE; printf("■■■"); RED; printf("■■■■■"); RED; printf("■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 8);
	RED; printf("■■"); WHITE; printf("■■■"); RED; printf("■■■"); WHITE; printf("★"); RED; printf("■■■"); WHITE; printf("★"); RED; printf("■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 9);
	RED; printf("■■"); WHITE; printf("■■■■"); RED; printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 10);
	RED; printf("■■■"); WHITE; printf("■■■■"); RED; printf("■■"); WHITE; printf("★"); RED; printf("■"); WHITE; printf("★"); RED; printf("■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 11);
	RED; printf("■■■■■"); WHITE; printf("■■■"); RED; printf("■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 12);
	RED; printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 13);
	WHITE; printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 14);
	WHITE; printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 15);
	WHITE; printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 16);
	WHITE; printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 17);
	WHITE; printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 18);
	WHITE; printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 19);
	WHITE; printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 20);
	WHITE; printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 21);
	WHITE; printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
} //싱가포르


void canada(){  //캐나다
	gotoxy(13, 3);
	RED; printf("■■■■"); WHITE; printf("■■■■■■■■■■■■"); WHITE; printf("■■■■■■■■■■■"); RED; printf("■■■■\n");
	gotoxy(13, 4);
	RED; printf("■■■■"); WHITE; printf("■■■■■■■■■■■"); RED; printf("■"); WHITE; printf("■■■■■■■■■■■"); RED; printf("■■■■\n");
	gotoxy(13, 5);
	RED; printf("■■■■"); WHITE; printf("■■■■■■■■■■"); RED; printf("■■■"); WHITE; printf("■■■■■■■■■■"); RED; printf("■■■■\n");
	gotoxy(13, 6);
	RED; printf("■■■■"); WHITE; printf("■■■■■■■"); RED; printf("■"); WHITE; printf("■■"); RED; printf("■■■"); WHITE; printf("■■"); RED; printf("■"); WHITE; printf("■■■■■■■"); RED; printf("■■■■\n");
	gotoxy(13, 7);
	RED; printf("■■■■"); WHITE; printf("■■■■■■"); RED; printf("■■■■■■■■■■■"); WHITE; printf("■■■■■■"); RED; printf("■■■■\n");
	gotoxy(13, 8);
	RED; printf("■■■■"); WHITE; printf("■■■■■■"); RED; printf("■■■■■■■■■■■"); WHITE; printf("■■■■■■"); RED; printf("■■■■\n");
	gotoxy(13, 9);
	RED; printf("■■■■"); WHITE; printf("■■■■■■■"); RED; printf("■■■■■■■■■"); WHITE; printf("■■■■■■■"); RED; printf("■■■■\n");
	gotoxy(13, 10);
	RED; printf("■■■■"); WHITE; printf("■■■"); RED; printf("■■"); WHITE; printf("■■■"); RED; printf("■■■■■■■"); WHITE; printf("■■■"); RED; printf("■■"); WHITE; printf("■■■"); RED; printf("■■■■\n");
	gotoxy(13, 11);
	RED; printf("■■■■"); WHITE; printf("■■"); RED; printf("■■■■■■■■■■■■■■■■■■■"); WHITE; printf("■■"); RED; printf("■■■■\n");
	gotoxy(13, 12);
	RED; printf("■■■■"); WHITE; printf("■■■"); RED; printf("■■■■■■■■■■■■■■■■■"); WHITE; printf("■■■"); RED; printf("■■■■\n");
	gotoxy(13, 13);
	RED; printf("■■■■"); WHITE; printf("■■■■"); RED; printf("■■■■■■■■■■■■■■■"); WHITE; printf("■■■■"); RED; printf("■■■■\n");
	gotoxy(13, 14);
	RED; printf("■■■■"); WHITE; printf("■■■■■"); RED; printf("■■■■■■■■■■■■■"); WHITE; printf("■■■■■"); RED; printf("■■■■\n");
	gotoxy(13, 15);
	RED; printf("■■■■"); WHITE; printf("■■■■"); RED; printf("■■■■■■■■■■■■■■■"); WHITE; printf("■■■■"); RED; printf("■■■■\n");
	gotoxy(13, 16);
	RED; printf("■■■■"); WHITE; printf("■■■"); RED; printf("■■■■■■■■■■■■■■■■■"); WHITE; printf("■■■"); RED; printf("■■■■\n");
	gotoxy(13, 17);
	RED; printf("■■■■"); WHITE; printf("■■■■■■■■■■■"); RED; printf("■"); WHITE; printf("■■■■■■■■■■■"); RED; printf("■■■■\n");
	gotoxy(13, 18);
	RED; printf("■■■■"); WHITE; printf("■■■■■■■■■■■"); RED; printf("■"); WHITE; printf("■■■■■■■■■■■"); RED; printf("■■■■\n");
	gotoxy(13, 19);
	RED; printf("■■■■"); WHITE; printf("■■■■■■■■■■■"); RED; printf("■"); WHITE; printf("■■■■■■■■■■■"); RED; printf("■■■■\n");
	gotoxy(13, 20);
	RED; printf("■■■■"); WHITE; printf("■■■■■■■■■■■"); RED; printf("■"); WHITE; printf("■■■■■■■■■■■"); RED; printf("■■■■\n");
	gotoxy(13, 21);
	RED; printf("■■■■"); WHITE; printf("■■■■■■■■■■■"); RED; printf("■"); WHITE; printf("■■■■■■■■■■■"); RED; printf("■■■■\n");
	gotoxy(13, 22);
	RED; printf("■■■■"); WHITE; printf("■■■■■■■■■■■■"); WHITE; printf("■■■■■■■■■■■"); RED; printf("■■■■\n");
} //캐나다

void australia() { //호주(오스트레일리아) 가로	31 세로 19
	gotoxy(13, 3);
	BLUE printf("■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■■"); WHITE printf("■"); RED printf("■■■"); WHITE printf("■"); BLUE printf("■■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 4);
	BLUE printf("■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■■"); WHITE printf("■"); RED printf("■■■"); WHITE printf("■"); BLUE printf("■■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 5);
	BLUE printf("■■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■");  WHITE printf("■"); RED printf("■■■"); WHITE printf("■"); BLUE printf("■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■■■■■■■■■■■"); WHITE printf("■"); BLUE printf("■■■■\n");
	gotoxy(13, 6);
	BLUE printf("■■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■");  WHITE printf("■"); RED printf("■■■"); WHITE printf("■"); BLUE printf("■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■■■■■■■■■■"); WHITE printf("■■■"); BLUE printf("■■■\n");
	gotoxy(13, 7);
	WHITE printf("■■■■■■■"); RED printf("■■■"); WHITE printf("■■■■■■■"); BLUE printf("■■■■■■■■■"); WHITE printf("■"); BLUE printf("■■■■\n");
	gotoxy(13, 8);
	RED printf("■■■■■■■■■■■■■■■■■"); BLUE printf("■■■■■■■■■■■■■■\n");
	gotoxy(13, 9);
	RED printf("■■■■■■■■■■■■■■■■■"); BLUE printf("■■■■■"); WHITE printf("■"); BLUE printf("■■■■■■■■\n");
	gotoxy(13, 10);
	WHITE printf("■■■■■■■"); RED printf("■■■"); WHITE printf("■■■■■■■"); BLUE printf("■■■■"); WHITE printf("■■■");BLUE printf("■■■■■■■\n");
	gotoxy(13, 11);
	BLUE printf("■■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■"); WHITE printf("■"); RED printf("■■■"); WHITE printf("■"); BLUE printf("■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■■■■■■■"); WHITE printf("■"); BLUE printf("■■■■■■■■\n");
	gotoxy(13, 12);
	BLUE printf("■■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■");  WHITE printf("■"); RED printf("■■■"); WHITE printf("■"); BLUE printf("■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 13);
	BLUE printf("■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■■"); WHITE printf("■"); RED printf("■■■"); WHITE printf("■"); BLUE printf("■■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■■■■■■■■■■■"); WHITE printf("■"); BLUE printf("■■■\n");
	gotoxy(13, 14);
	BLUE printf("■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■■"); WHITE printf("■"); RED printf("■■■"); WHITE printf("■");  BLUE printf("■■"); WHITE printf("■"); RED printf("■"); WHITE printf("■"); BLUE printf("■■■■■■■■■■"); WHITE printf("■■■");BLUE printf("■■\n");
	gotoxy(13, 15);
	BLUE printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■"); WHITE printf("■"); BLUE printf("■■■\n");
	gotoxy(13, 16);
	BLUE printf("■■■■■■■■■■■■■■■■■■■■"); WHITE printf("■"); BLUE printf ("■■■■■■■■■■\n");
	gotoxy(13, 17);
	BLUE printf("■■■■■■■■■"); WHITE printf("■"); BLUE printf("■■■■■■■■■"); WHITE printf("■■■"); BLUE printf("■■■■■■■■■\n");
	gotoxy(13, 18);
	BLUE printf("■■■■■■■■"); WHITE printf("■■■"); BLUE printf("■■■■■■■■■"); WHITE printf("■"); BLUE printf("■■■■"); WHITE printf("■"); BLUE printf("■■■■■\n");
	gotoxy(13, 19);
	BLUE printf("■■■■■■■■■"); WHITE printf("■"); BLUE printf("■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 20);
	BLUE printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 21);
	BLUE printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
}

void philippines(){  //필리핀 가로 30 세로 20
	gotoxy(13, 3);
	WHITE printf("■■");BLUE printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 4);
	WHITE printf("■■■■"); BLUE printf("■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 5);
	WHITE printf("■■■■■");BLUE printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 6);
	WHITE printf("■■■■■■■");BLUE printf("■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 7);
	WHITE printf("■■■■■■■■"); BLUE printf("■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 8);
	WHITE printf("■■"); YELLOW printf("★"); WHITE printf("■■■■■■■"); BLUE printf("■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 9);
	WHITE printf("■■■■■■■■■■■"); BLUE printf("■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 10);
	WHITE printf("■■■■■"); YELLOW printf("■"); WHITE printf("■■■■■■■");BLUE printf("■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 11);
	WHITE printf("■■■"); YELLOW printf("■"); WHITE printf("■"); YELLOW printf("■"); WHITE printf("■"); YELLOW printf("■"); WHITE printf("■■■■■■");BLUE printf("■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 12);
	WHITE printf("■■■■");  YELLOW printf("■■■"); WHITE printf("■■■"); YELLOW printf("★"); WHITE printf("■■■■■");BLUE printf("■■■■■■■■■■■■■■\n");
	gotoxy(13, 13);
	WHITE printf("■■■■");  YELLOW printf("■■■"); WHITE printf("■■■■■■■■■"); RED printf("■■■■■■■■■■■■■■\n");
	gotoxy(13, 14);
	WHITE printf("■■■"); YELLOW printf("■"); WHITE printf("■"); YELLOW printf("■"); WHITE printf("■"); YELLOW printf("■"); WHITE printf("■■■■■■"); RED printf("■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 15);
	WHITE printf("■■■■■"); YELLOW printf("■"); WHITE printf("■■■■■■■"); RED printf("■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 16);
	WHITE printf("■■■■■■■■■■■"); RED printf("■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 17);
	WHITE printf("■■"); YELLOW printf("★"); WHITE printf("■■■■■■■"); RED printf("■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 18);
	WHITE printf("■■■■■■■■"); RED printf("■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 19);
	WHITE printf("■■■■■■■"); RED printf("■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 20);
	WHITE printf("■■■■■");RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 21);
	WHITE printf("■■■■"); RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 22);
	WHITE printf("■■"); RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
}



void france() { //프랑스 가로30 세로 21
	gotoxy(13, 3);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 4);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 5);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 6);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 7);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 8);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 9);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 10);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 11);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 12);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 13);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 14);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 15);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 16);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 17);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 18);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 19);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 20);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 21);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 22);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 23);
	BLUE printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
}

void portugal(){ //포르투갈 가로 30 세로 20
	gotoxy(13, 3);
	GREEN printf("■■■■■■■■■■"); BLOOD printf("■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 4);
	GREEN printf("■■■■■■■■■■"); BLOOD printf("■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 5);
	GREEN printf("■■■■■■■■■■"); BLOOD printf("■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 6);
	GREEN printf("■■■■■■■■■■"); BLOOD printf("■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 7);
	GREEN printf("■■■■■■■■■■"); BLOOD printf("■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 8);
	GREEN printf("■■■■■■■■■■"); BLOOD printf("■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 9);
	GREEN printf("■■■■■■■"); YELLOW printf("■■■■■"); BLOOD printf("■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 10);
	GREEN printf("■■■■■■"); YELLOW printf("■■■"); GREEN printf("■"); YELLOW printf("■■■■"); BLOOD printf("■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 11);
	GREEN printf("■■■■■"); YELLOW printf("■"); GREEN printf("■■■"); BLOOD printf("■■"); YELLOW printf("■"); BLOOD printf("■■"); YELLOW printf("■"); BLOOD printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 12);
	GREEN printf("■■■■■"); YELLOW printf("■■■"); BLOOD printf("■"); WHITE printf("■■"); BLOOD printf("■"); YELLOW printf("■"); BLOOD printf("■"); YELLOW printf("■"); BLOOD printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 13);
	GREEN printf("■■■■■"); YELLOW printf("■"); GREEN printf("■■"); BLOOD printf("■"); WHITE printf("■■"); BLOOD printf("■"); YELLOW printf("■■■"); BLOOD printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 14);
	GREEN printf("■■■■■"); YELLOW printf("■"); GREEN printf("■■"); YELLOW printf("■"); BLOOD printf("■■"); YELLOW printf("■"); BLOOD printf("■■"); YELLOW printf("■"); BLOOD printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 15);
	GREEN printf("■■■■■■"); YELLOW printf("■■"); GREEN printf("■■"); BLOOD printf("■■"); YELLOW printf("■■"); BLOOD printf("■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 16);
	GREEN printf("■■■■■■■■"); YELLOW printf("■■■■"); BLOOD printf("■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 17);
	GREEN printf("■■■■■■■■■■"); BLOOD printf("■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 18);
	GREEN printf("■■■■■■■■■■"); BLOOD printf("■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 19);
	GREEN printf("■■■■■■■■■■"); BLOOD printf("■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 20);
	GREEN printf("■■■■■■■■■■"); BLOOD printf("■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 21);
	GREEN printf("■■■■■■■■■■"); BLOOD printf("■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 22);
	GREEN printf("■■■■■■■■■■"); BLOOD printf("■■■■■■■■■■■■■■■■■■■■\n");
}

void china() { //중국 가로 30 세로 20
	gotoxy(13, 3);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 4);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 5);
	RED printf("■■■■■■■■■■■■"); YELLOW printf("★"); RED printf("■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 6);
	RED printf("■■■■■"); YELLOW printf("★"); RED printf("■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 7);
	RED printf("■■■■■"); YELLOW printf("★"); RED printf("■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 8);
	RED printf("■■"); YELLOW printf("★"); RED printf("■"); YELLOW printf("★★★"); RED printf("■"); YELLOW printf("★"); RED printf("■■■■■"); YELLOW printf("★"); RED printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 9);
	RED printf("■■■"); YELLOW printf("★★★★★");RED printf("■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 10);
	RED printf("■■■■"); YELLOW printf("★★★");RED printf("■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 11);
	RED printf("■■■■"); YELLOW printf("★"); RED printf("■"); YELLOW printf("★"); RED printf("■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 12);
	RED printf("■■■"); YELLOW printf("★"); RED printf("■■■"); YELLOW printf("★"); RED printf("■■■■■■"); YELLOW printf("★"); RED printf("■■■■■■■■■■■■■■■\n");
	gotoxy(13, 13);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 14);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 15);
	RED printf("■■■■■■■■■■■■"); YELLOW printf("★"); RED printf("■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 16);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 17);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 18);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 19);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 20);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 21);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 22);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
}

void japan()//일본 가로 30 세로 20
{   gotoxy(13, 3);
	WHITE printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 4);
	WHITE printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 5);
	WHITE printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 6);
	WHITE printf("■■■■■■■■■■■■"); RED printf("■■■■■■"); WHITE; printf("■■■■■■■■■■■■\n");
	gotoxy(13, 7);
	WHITE printf("■■■■■■■■■■■"); RED printf("■■■■■■■■");WHITE printf("■■■■■■■■■■■\n");
	gotoxy(13, 8);
	WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■");WHITE printf("■■■■■■■■■■\n");
	gotoxy(13, 9);
	WHITE printf("■■■■■■■■■"); RED printf("■■■■■■■■■■■■");WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 10);
	WHITE printf("■■■■■■■■■"); RED printf("■■■■■■■■■■■■");WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 11);
	WHITE printf("■■■■■■■■■"); RED printf("■■■■■■■■■■■■");WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 12);
	WHITE printf("■■■■■■■■■"); RED printf("■■■■■■■■■■■■"); WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 13);
	WHITE printf("■■■■■■■■■"); RED printf("■■■■■■■■■■■■"); WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 14);
	WHITE printf("■■■■■■■■■"); RED printf("■■■■■■■■■■■■"); WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 15);
	WHITE printf("■■■■■■■■■"); RED printf("■■■■■■■■■■■■"); WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 16);
	WHITE printf("■■■■■■■■■"); RED printf("■■■■■■■■■■■■"); WHITE printf("■■■■■■■■■\n");
	gotoxy(13, 17);
	WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■\n");
	gotoxy(13, 18);
	WHITE printf("■■■■■■■■■■■"); RED printf("■■■■■■■■"); WHITE printf("■■■■■■■■■■■\n");
	gotoxy(13, 19);
	WHITE printf("■■■■■■■■■■■■"); RED printf("■■■■■■"); WHITE printf("■■■■■■■■■■■■\n");
	gotoxy(13, 20);
	WHITE printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 21);
	WHITE printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 22);
	WHITE printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
}

void italy() { // 이탈리아 가로30 세로 21
	gotoxy(13, 3);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 4);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 5);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 6);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 7);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 8);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 9);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 10);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 11);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 12);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 13);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 14);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 15);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 16);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 17);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 18);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 19);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 20);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 21);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 22);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
	gotoxy(13, 23);
	GREEN printf("■■■■■■■■■■"); WHITE printf("■■■■■■■■■■"); RED printf("■■■■■■■■■■\n");
}

void united_kingdom(){ //영국 가로31 세로 17
	gotoxy(13, 3);
	RED printf("■■"); WHITE printf("■■"); BLUE printf("■■■■■■■■"); WHITE printf("■"); RED printf("■■■■■"); WHITE printf("■"); BLUE printf("■■■■■■■■"); WHITE printf("■■"); RED printf("■■\n");
	gotoxy(13, 4);
	WHITE printf("■■"); RED printf("■■"); WHITE printf("■■"); BLUE printf("■■■■■■"); WHITE printf("■"); RED printf("■■■■■"); WHITE printf("■"); BLUE printf("■■■■■■"); WHITE printf("■■"); RED printf("■■"); WHITE printf("■■\n");
	gotoxy(13, 5);
	BLUE printf("■■"); WHITE printf("■■"); RED printf("■■"); WHITE printf("■■"); BLUE printf("■■■■"); WHITE printf("■"); RED printf("■■■■■"); WHITE printf("■"); BLUE printf("■■■■"); WHITE printf("■■"); RED printf("■■"); WHITE printf("■■"); BLUE printf("■■\n");
	gotoxy(13, 6);
	BLUE printf("■■■■"); WHITE printf("■■"); RED printf("■■"); WHITE printf("■■■");	BLUE printf("■"); WHITE printf("■"); RED printf("■■■■■"); WHITE printf("■"); BLUE printf("■"); WHITE("■");  WHITE printf("■■■"); RED printf("■■");  WHITE printf("■■"); BLUE printf("■■■■\n");
	gotoxy(13, 7);
	BLUE printf("■■■■■■"); WHITE printf("■■"); RED printf("■■"); WHITE printf("■"); BLUE printf("■"); WHITE printf("■"); RED printf("■■■■■");  WHITE printf("■");  BLUE printf("■"); WHITE printf("■"); RED printf("■■"); WHITE printf("■■"); BLUE printf("■■■■■■\n");
	gotoxy(13, 8);
	WHITE printf("■■■■■■■■■■■■■"); RED printf("■■■■■"); WHITE printf("■■■■■■■■■■■■■\n");
	gotoxy(13, 9);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 10);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 11);	
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 12);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 13);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 14);
	WHITE printf("■■■■■■■■■■■■■"); RED printf("■■■■■"); WHITE printf("■■■■■■■■■■■■■\n");
	gotoxy(13, 15);
	BLUE printf("■■■■■■"); WHITE printf("■■"); RED printf("■■"); WHITE printf("■"); BLUE printf("■"); WHITE printf("■"); RED printf("■■■■■"); WHITE printf("■");  BLUE printf("■"); WHITE printf("■"); RED printf("■■"); WHITE printf("■■"); BLUE printf("■■■■■■\n");
	gotoxy(13, 16);
	BLUE printf("■■■■"); WHITE printf("■■"); RED printf("■■"); WHITE printf("■■■");	BLUE printf("■"); WHITE printf("■"); RED printf("■■■■■"); WHITE printf("■"); BLUE printf("■"); WHITE("■");  WHITE printf("■■■"); RED printf("■■");  WHITE printf("■■"); BLUE printf("■■■■\n");
	gotoxy(13, 17);
	BLUE printf("■■"); WHITE printf("■■"); RED printf("■■"); WHITE printf("■■"); BLUE printf("■■■■"); WHITE printf("■"); RED printf("■■■■■"); WHITE printf("■"); BLUE printf("■■■■"); WHITE printf("■■"); RED printf("■■"); WHITE printf("■■"); BLUE printf("■■\n");
	gotoxy(13, 18);
	WHITE printf("■■"); RED printf("■■"); WHITE printf("■■"); BLUE printf("■■■■■■"); WHITE printf("■"); RED printf("■■■■■"); WHITE printf("■"); BLUE printf("■■■■■■"); WHITE printf("■■"); RED printf("■■"); WHITE printf("■■\n");
	gotoxy(13, 19);
	RED printf("■■"); WHITE printf("■■"); BLUE printf("■■■■■■■■"); WHITE printf("■"); RED printf("■■■■■"); WHITE printf("■"); BLUE printf("■■■■■■■■"); WHITE printf("■■"); RED printf("■■\n");
	gotoxy(13, 20);

}


void brazil(){ //브라질 가로 30 세로 19
	gotoxy(13, 3);
	GREEN printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 4);
	GREEN printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 5);
	GREEN printf("■■■■■■■■■■■■■■"); YELLOW printf("■■"); GREEN printf("■■■■■■■■■■■■■■\n");
	gotoxy(13, 6);
	GREEN printf("■■■■■■■■■■■■"); YELLOW printf("■■■■■■"); GREEN printf("■■■■■■■■■■■■\n");
	gotoxy(13, 7);
	GREEN printf("■■■■■■■■■■■"); YELLOW printf("■■■■■■■■"); GREEN printf("■■■■■■■■■■■\n");
	gotoxy(13, 8);
	GREEN printf("■■■■■■■■■"); YELLOW printf("■■■■■"); BLUE printf("■■"); YELLOW printf("■■■■■"); GREEN printf("■■■■■■■■■\n");
	gotoxy(13, 9);
	GREEN printf("■■■■■■■■"); YELLOW printf("■■■■■"); BLUE printf("■■■■"); YELLOW printf("■■■■■");GREEN printf("■■■■■■■■\n");
	gotoxy(13, 10);
	GREEN printf("■■■■■■"); YELLOW printf("■■■■■■"); BLUE printf("■■■■■■"); YELLOW printf("■■■■■■");GREEN printf("■■■■■■\n");
	gotoxy(13, 11);
	GREEN printf("■■■■■"); YELLOW printf("■■■■■■"); BLUE printf("■"); WHITE printf("■■■"); BLUE printf("■■■■"); YELLOW printf("■■■■■■");GREEN printf("■■■■■\n");
	gotoxy(13, 12);
	GREEN printf("■■■■"); YELLOW printf("■■■■■■"); BLUE printf("■■"); WHITE printf("★");BLUE printf("■■"); WHITE printf("■"); BLUE printf("■"); WHITE printf("★");BLUE printf("■■"); YELLOW printf("■■■■■■");GREEN printf("■■■■\n");
	gotoxy(13, 13);
	GREEN printf("■■■■■"); YELLOW printf("■■■■■■"); BLUE printf("■■■■■"); WHITE printf("■■"); BLUE printf("■"); YELLOW printf("■■■■■■"); GREEN printf("■■■■■\n");
	gotoxy(13, 14);
	GREEN printf("■■■■■■"); YELLOW printf("■■■■■■"); BLUE printf("■"); WHITE printf("★"); BLUE printf("■■"); WHITE printf("★"); BLUE printf("■"); YELLOW printf("■■■■■■"); GREEN printf("■■■■■■\n");
	gotoxy(13, 15);
	GREEN printf("■■■■■■■■"); YELLOW printf("■■■■■"); BLUE printf("■■"); WHITE printf("★");BLUE printf("■"); YELLOW printf("■■■■■"); GREEN printf("■■■■■■■■\n");
	gotoxy(13, 16);
	GREEN printf("■■■■■■■■■"); YELLOW printf("■■■■■"); BLUE printf("■■"); YELLOW printf("■■■■■");GREEN printf("■■■■■■■■■\n");
	gotoxy(13, 17);
	GREEN printf("■■■■■■■■■■■"); YELLOW printf("■■■■■■■■"); GREEN printf("■■■■■■■■■■■\n");
	gotoxy(13, 18);
	GREEN printf("■■■■■■■■■■■■"); YELLOW printf("■■■■■■"); GREEN printf("■■■■■■■■■■■■\n");
	gotoxy(13, 19);
	GREEN printf("■■■■■■■■■■■■■■"); YELLOW printf("■■"); GREEN printf("■■■■■■■■■■■■■■\n");
	gotoxy(13, 20);
	GREEN printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 21);
	GREEN printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
}


void spain(){ //스폐인 가로 30 세로 19
	gotoxy(13, 3);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 4);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 5);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 6);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 7);
	YELLOW printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 8);
	YELLOW printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 9);
	YELLOW printf("■■■■■■"); RED printf("■■■"); YELLOW printf("■"); RED printf("■■■"); YELLOW printf("■"); RED printf("■■■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■■"); RED printf("■"); YELLOW printf("■■■■■■\n");
	gotoxy(13, 10);
	YELLOW printf("■■■■■■"); RED printf("■"); YELLOW printf("■■■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■■"); RED printf("■"); YELLOW printf("■■■■■■\n");
	gotoxy(13, 11);
	YELLOW printf("■■■■■■"); RED printf("■"); YELLOW printf("■■■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■■"); RED printf("■"); YELLOW printf("■■■■■■\n");
	gotoxy(13, 12);
	YELLOW printf("■■■■■■"); RED printf("■■■");  YELLOW printf("■"); RED printf("■■■"); YELLOW printf("■"); RED printf("■■■");  YELLOW printf("■"); RED printf("■"); YELLOW printf("■"); RED printf("■■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■■■■■■\n");
	gotoxy(13, 13);
	YELLOW printf("■■■■■■■■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■■■"); RED printf("■");  YELLOW printf("■"); RED printf("■");  YELLOW printf("■"); RED printf("■");  YELLOW printf("■"); RED printf("■");  YELLOW printf("■"); RED printf("■■");YELLOW printf("■■■■■■\n");
	gotoxy(13, 14);
	YELLOW printf("■■■■■■■■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■■■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■■"); RED printf("■"); YELLOW printf("■■■■■■\n");
	gotoxy(13, 15);
	YELLOW printf("■■■■■■"); RED printf("■■■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■■■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■"); RED printf("■"); YELLOW printf("■■"); RED printf("■"); YELLOW printf("■■■■■■\n");
	gotoxy(13, 16);
	YELLOW printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 17);
	YELLOW printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 18);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 19);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 20);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	gotoxy(13, 21);
	RED printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
}





void uninhabited() { //무인도 가로30 세로 21
	WHITE printf("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■\n");
	WHITE printf("■■■■■■■■■■■■■■■■■■■"); BLACK printf("■"); WHITE printf("■■■■■■■■■■\n");
	WHITE printf("■■■■■■■■■■■■■■■■■■"); BLACK printf("■"); GREEN printf("■"); BLACK printf("■"); WHITE printf("■■■■■■■■■\n");
	WHITE printf("■■■■■■■■■■■■■■■■■■"); BLACK printf("■"); GREEN printf("■"); BLACK printf("■"); WHITE printf("■■■■■■■■■\n");
	WHITE printf("■■■■■■■■■■■■■■"); BLACK printf("■■■"); WHITE printf("■"); BLACK printf("■"); GREEN printf("■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■■■"); WHITE printf("■■■■■\n");
	WHITE printf("■■■■■■■■■■■■■"); BLACK printf("■"); GREEN printf("■■■");  BLACK printf("■■"); GREEN printf("■"); BLACK printf("■■"); GREEN printf("■■■"); BLACK printf("■"); WHITE printf("■■■■\n");
	WHITE printf("■■■■■■■■■■■■■■"); BLACK printf("■■"); GREEN printf("■■"); BLACK printf("■"); GREEN printf("■"); BLACK printf("■"); GREEN printf("■■"); BLACK printf("■■"); WHITE printf("■■■■■\n");
	WHITE printf("■■■■■■■■■■■■■■■■"); BLACK printf("■"); GREEN printf("■■"); BLACK printf("■"); GREEN printf("■■"); BLACK printf("■"); WHITE printf("■■■■■■■\n");
	WHITE printf("■■■■■■■"); RED printf("■■"); WHITE printf("■■■■■■■■"); BLACK printf("■"); GREEN printf("■"); BLACK printf("■"); GREEN printf("■"); BLACK printf("■"); WHITE printf("■■■■■■■■\n");
	WHITE printf("■■■■■■"); RED printf("■■■■"); WHITE printf("■■■■■■■■"); BLACK printf("■■■"); WHITE printf("■■■■■■■■■\n");
	WHITE printf("■■■■■■"); RED printf("■■■■"); WHITE printf("■■■■■■■■■"); BLACK printf("■"); WHITE printf("■■■■■■■■■■\n");
	WHITE printf("■■■■■■■"); RED printf("■■"); WHITE printf("■■■■■■■■■■"); BLACK printf("■"); WHITE printf("■■■■■■■■■■\n");
	WHITE printf("■■■■■■■■■■■■■■■■■■■"); BLACK printf("■");WHITE printf("■■■■■■■■■■\n");
	WHITE printf("■■■■■■■■■■■■■■■■■■■"); BLACK printf("■"); WHITE printf("■■■■■■■■■■\n");
	WHITE printf("■■■■■■■■■■■■■■■■■■■"); BLACK printf("■"); WHITE printf("■■■■■■■■■■\n");
	WHITE printf("■■■■■■■■■■■■■■■■■■■"); BLACK printf("■"); WHITE printf("■■■■■■■■■■\n");
	WHITE printf("■■■■■■■■■■■■■■■"); BLACK printf("■■"); GOLD printf("■■■■■"); BLACK printf("■■"); WHITE printf("■■■■■■\n");
	WHITE printf("■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■"); WHITE printf("■"); BLACK printf("■■"); GOLD printf("■■■■■■■■■"); BLACK printf("■■■■"); WHITE printf("■■\n");
	BLACK printf("■"); BLUE printf("■"); BLACK printf("■"); BLUE printf("■"); BLACK printf("■"); BLUE printf("■"); BLACK printf("■"); BLUE printf("■"); BLACK printf("■"); BLUE printf("■"); BLACK printf("■"); BLUE printf("■"); BLACK printf("■"); GOLD printf("■■■■■■■■■■■■■■■"); BLACK printf("■■\n");
	BLUE printf("■■■■■■■■■■■■■"); GOLD printf("■■■■■■■■■■■■■■■■■\n");
}